# Generated by Django 5.2.14 on 2026-05-29 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0150_part_maximum_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', help_text='Código de barras gerado por software externo (apenas para consulta)', max_length=32, validators=[django.core.validators.RegexValidator('^\\d*$', 'Informe apenas dígitos numéricos')], verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='part',
            name='cor',
            field=models.CharField(blank=True, choices=[('preto', 'Preto'), ('azul', 'Azul'), ('rosa', 'Rosa')], default='', help_text='Cor do produto', max_length=20, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='part',
            name='fob',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor FOB em dólar (US$)', max_digits=12, null=True, verbose_name='FOB (US$)'),
        ),
        migrations.AddField(
            model_name='part',
            name='material_corpo',
            field=models.CharField(blank=True, default='', help_text='Material do corpo do produto', max_length=100, verbose_name='Material Corpo'),
        ),
        migrations.AddField(
            model_name='part',
            name='material_forro',
            field=models.CharField(blank=True, default='', help_text='Material do forro do produto', max_length=100, verbose_name='Material Forro'),
        ),
        migrations.AddField(
            model_name='part',
            name='name_en',
            field=models.CharField(blank=True, default='', help_text='Nome do produto em inglês', max_length=100, verbose_name='Nome - Inglês'),
        ),
        migrations.AddField(
            model_name='part',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso do produto', max_digits=10, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True, help_text='Part description (optional)', verbose_name='Description'),
        ),
    ]
